export const HOME_MENU_ITEMS = [
  'A/B Testing',
  'Add/Remove Elements',
  'Basic Auth',
  'Broken Images',
  'Challenging DOM',
  'Checkboxes',
  'Context Menu',
  'Digest Authentication',
  'Disappearing Elements',
  'Drag and Drop',
  'Dropdown',
  'Dynamic Content',
  'Dynamic Controls',
  'Dynamic Loading',
  'Entry Ad',
  'Exit Intent',
  'File Download',
  'File Upload',
  'Floating Menu',
  'Forgot Password',
  'Form Authentication',
  'Frames',
  'Geolocation',
  'Horizontal Slider',
  'Hovers',
  'Infinite Scroll',
  'Inputs',
  'JQuery UI Menus',
  'JavaScript Alerts',
  'JavaScript onload event error',
  'Key Presses',
  'Large & Deep DOM',
  'Multiple Windows',
  'Nested Frames',
  'Notification Messages',
  'Redirect Link',
  'Secure File Download',
  'Shadow DOM',
  'Shifting Content',
  'Slow Resources',
  'Sortable Data Tables',
  'Status Codes',
  'Typos',
  'WYSIWYG Editor'
]

export const FRAMES_MENU_ITEMS = [
  'Nested Frames',
  'iFrame',
]

export const PAGES_PATH = {
  frames: 'frames',
  nestedFrames: 'nested_frames',
  iframe: 'iframe',
  basicAuth: 'basic_auth',
}